### ISSUE TITLE
お題の種

### ISSUE THREAD

**Issue by willnet** [ginzarb/meetups#122]
なんかRuby関連で面白そうな記事やサイトあったら貼り付けるスレです

**Comment by willnet** [comment]
[Ruby on Rails Hosting & App Deployment - Ninefold](https://ninefold.com/)

- herokuっぽいPaas
- 無料枠ある
- rails限定だけど、herokuより無料でよいサーバ使えるぽい

**Comment by y-yagi** [comment]
http://www.codingame.com/home

* シューティングゲームを題材にプログラミングを学べるサービス
* 割と主要な言語は使える(Go、Dart、Pascalなんかもある). 当然Rubyも.
* 慣れが必要そうですが、みんなでワイワイやるの良さそう

**Comment by willnet** [comment]
[eliotsykes/rspec-rails-examples](https://github.com/eliotsykes/rspec-rails-examples)

**Comment by willnet** [comment]
http://www.publickey1.jp/blog/16/google_app_enginerubynodejsgcp_next_2016.html

**Comment by willnet** [comment]
あとこれも [IBM Bluemixトライアル：サインアップ](https://developer.ibm.com/sso/bmregistration?lang=ja_JP&ca=dwjapan-_-bluemix-_-cl-blograils-app-_-article)

**Comment by y-yagi** [comment]
おー、IBMこんなのやってるんですねえ

**Comment by y-yagi** [comment]
[Otto by HashiCorp](https://www.ottoproject.io/)

**Comment by willnet** [comment]
デザパタ

[Ruby 2.0.0で学ぶ、14個のデザインパターンを作りました[GoF][Design Pattern] - 酒と泪とRubyとRailsと](http://morizyun.github.io/blog/ruby-design-pattern-matome-mokuzi/)

**Comment by willnet** [comment]
cron replacement 系

- [tomykaira/clockwork: A scheduler process to replace cron.](https://github.com/tomykaira/clockwork)
- [moove-it/sidekiq-scheduler: Lightweight job scheduler extension for Sidekiq](https://github.com/moove-it/sidekiq-scheduler)

**Comment by willnet** [comment]
bundler とか gem (コマンドの方)とか、日常的に使っているツールのオプションを全部確認する回とかどうか

**Comment by y-yagi** [comment]
[Domain Driven Design（ドメイン駆動設計） Quickly 日本語版](https://www.infoq.com/jp/minibooks/domain-driven-design-quickly) 
見ながら、Rails でDDDやる場合どうすんのが良いですかね、みたいなふわっとした話

**Comment by willnet** [comment]
[Cloud9 - Your development environment, in the cloud](https://c9.io/)

**Comment by y-yagi** [comment]
[andypike/rectify: Build maintainable Rails apps](https://github.com/andypike/rectify)

**Comment by y-yagi** [comment]
[crystal-lang/crystal: The Crystal Programming Language](https://github.com/crystal-lang/crystal)

**Comment by y-yagi** [comment]
[opal/opal: Ruby to JavaScript compiler](https://github.com/opal/opal)

**Comment by y-yagi** [comment]
Railsのperformanceチューニングについての情報共有会

**Comment by willnet** [comment]
[The Complete Guide to Rails Performance](https://www.railsspeed.com/) を読むときが来たかもしれない

**Comment by y-yagi** [comment]
(ちょうど読んでたのでした)

**Comment by y-yagi** [comment]
RubyKaigi 2016の感想を言う会。 プレゼン資料が上がってからが良さそう。

**Comment by willnet** [comment]
> RubyKaigi 2016の感想を言う会

次回 9/20 だしちょうど良さそう

**Comment by willnet** [comment]
リファクタリング

[jimweirich/gilded_rose_kata: The Gilded Rose Code Cata](https://github.com/jimweirich/gilded_rose_kata)

**Comment by y-yagi** [comment]
Pumaコードリーディング

**Comment by y-yagi** [comment]
[Ruby Tutorials \- Semaphore](https://semaphoreci.com/community/tags/ruby)を見る

**Comment by y-yagi** [comment]
たまにはscalaとかどうっすか
[Scala Warriorをリリースしました \- たけぞう瀕死ブログ](http://takezoe.hatenablog.com/entry/2016/10/11/081836)

**Comment by willnet** [comment]
[Crystal](http://ja.crystal-lang.org/)

**Comment by willnet** [comment]
1.0 でたら
[heckpsi-lab/em-midori: Lightweight, Flexible and Fast Ruby Web Framework](https://github.com/heckpsi-lab/em-midori)

**Comment by y-yagi** [comment]
Railsアプリのベンチマークのとりかた

[noahgibbs/rails\_ruby\_bench: A spike toward a Rails\-based benchmark for Ruby development](https://github.com/noahgibbs/rails_ruby_bench)
とか
[schneems/derailed\_benchmarks: Go faster, off the Rails \- Benchmarks for your whole Rails app](https://github.com/schneems/derailed_benchmarks)
あたりを試しながら

**Comment by willnet** [comment]
(進め方難しそうだけど) [Rubyソースコード完全解説](http://i.loveruby.net/ja/rhg/book/)

**Comment by koic** [comment]
RHG が厚くて進めづらいということであれば、拡張ライブラリの作り方の README となる以下があるのですが、周辺の知識がないと (別の意味で) 進めづらいかもしれません。
https://github.com/ruby/ruby/blob/trunk/doc/extension.ja.rdoc

**Comment by willnet** [comment]
[tootsuite/mastodon: A GNU Social-compatible microblogging server](https://github.com/tootsuite/mastodon)

**Comment by willnet** [comment]
↑かぶってた

**Comment by ttanimichi** [comment]
mastodon のソースコードリーディングやりたいですね

**Comment by ttanimichi** [comment]
あるいは OStatus に関連するプロトコルを学ぶ会

**Comment by willnet** [comment]
[orgsync/active_interaction: Manage application specific business logic.](https://github.com/orgsync/active_interaction)

**Comment by y-yagi** [comment]
https://github.com/Shopify
が作ってるgemをながめる

**Comment by willnet** [comment]
https://github.com/infinum/rails-handbook

**Comment by y-yagi** [comment]
package.json みせっこ

**Comment by onk** [comment]
読んでみたいレールズプロダクト。

https://github.com/alphagov/whitehall
https://github.com/annict/annict
https://github.com/catarse/catarse
https://github.com/discourse/discourse
https://github.com/feedbin/feedbin
https://github.com/gitlabhq/gitlabhq
https://github.com/hummingbird-me/hummingbird-server
https://github.com/ruby-china/homeland
https://github.com/shirasagi/shirasagi

**Comment by willnet** [comment]
https://twitter.com/sinsoku_listy/status/940037639167549440

> Railsアプリで「こういう時、どう実装するのが綺麗なのか？」みたいな現実感ある事例を各自が持ち寄って、それに対する意見を出す場というか、そんなの。nested_attributes_for、bulk_insert、複雑なview、非同期処理をどこに書くの？的な。

💭 お題を揃えるのが課題

**Comment by ttanimichi** [comment]
> Railsアプリで「こういう時、どう実装するのが綺麗なのか？」

関係ありそうなので貼っておきます

Rails AntiPatterns
https://www.amazon.co.jp/Rails-AntiPatterns-Refactoring-Addison-Wesley-Professional/dp/0321604814

これ英語圏だと有名な本みたいなんですけど日本語に翻訳されてないんですよね

**Comment by ttanimichi** [comment]
（レールから脱線してる列車の絵が良いですね）

**Comment by willnet** [comment]
とりあえずポチりました

**Comment by y-yagi** [comment]
bitcoin protocol/network を学ぶ
https://github.com/lian/bitcoin-ruby

仮想通貨どうこうを抜きにしても、ブロックチェーンについて学ぶのは、勉強になりそうな気はする。
ただ、やりかたが難そう。

**Comment by willnet** [comment]
ここがつらいよRails

**Comment by koic** [comment]
TRICK の過去作品研究。
https://github.com/tric

**Comment by ttanimichi** [comment]
Action Text

**Comment by willnet** [comment]
[Securing Sensitive Data in Rails](https://ankane.org/sensitive-data-rails)

セキュリティの話題(↑は個人情報系をどう扱うかの話)

**Comment by willnet** [comment]
[Red Hatが開発するDocker互換の新コンテナエンジン「Podman」、バージョン1.0に到達 － Publickey](https://www.publickey1.jp/blog/19/red_hatdockerpodman10.html)

**Comment by willnet** [comment]
[Jets Ruby Serverless Framework](http://rubyonjets.com/#page-top)

**Comment by willnet** [comment]
[mperham/sidekiq.cr: Simple, efficient job processing for Crystal](https://github.com/mperham/sidekiq.cr)

**Comment by willnet** [comment]
https://github.com/socketry/falcon

**Comment by willnet** [comment]
1.0出たらしい [Opal: Ruby ♥︎ JavaScript](http://opalrb.com/)

**Comment by willnet** [comment]
https://fullstaqruby.org/
