### ISSUE TITLE
お題

### ISSUE THREAD

**Issue by willnet** [ginzarb/meetups#15]
ミートアップのお題になりそうなものを思いついたらメモっておくスレです

**Comment by y-yagi** [comment]
Ruby 2.2の変更点を眺める
https://www.ruby-lang.org/ja/news/2014/12/25/ruby-2-2-0-released/
https://github.com/ruby/ruby/blob/v2_2_0/NEWS

**Comment by willnet** [comment]
https://github.com/phusion/traveling-ruby を触ってみる

**Comment by willnet** [comment]
それぞれの参加者に、その人がその月に書いたブログの内容をシェアしてもらうとかどうか

**Comment by y-yagi** [comment]
英語のPodcastを皆で聞いて、内容について雑談する。

[The Bike Shed](http://bikeshed.fm/)とか。

**Comment by willnet** [comment]
> 英語のPodcastを皆で聞いて、内容について雑談する。

昔 sendagaya.rb でやってたメソッドですね( ˘ω˘) あれは [Ruby5](https://ruby5.codeschool.com/) だったかな

**Comment by y-yagi** [comment]
> 昔 sendagaya.rb でやってたメソッド

おお、そうなんですね！ 知らなかった(\( ㆁөㆁ)/)

**Comment by willnet** [comment]
[tenderlove/the_metal](https://github.com/tenderlove/the_metal) を読む

**Comment by y-yagi** [comment]
[RailsConf 2015](http://railsconf.com/)の資料/動画を見る

**Comment by y-yagi** [comment]
Rails Engineについて

**Comment by y-yagi** [comment]
ActionCable がオープンになったようなので、ActionCableのコードリーディング(又は内容把握的な)
[Action Cable – Integrated websockets for Rails](https://github.com/rails/actioncable)

**Comment by y-yagi** [comment]
OSSになっているRailsアプリのコードを眺めてみる

例)
* [alphagov/e-petitions](https://github.com/alphagov/e-petitions)
* [alphagov/whitehall](https://github.com/alphagov/whitehall)
* [gitlabhq/gitlabhq](https://github.com/gitlabhq/gitlabhq)
とか

**Comment by y-yagi** [comment]
Rails で書かれたオープンソースのサービスを一覧できるサイトらしい
[Open Source Rails](http://www.opensourcerails.com/)
githubへのリンクも書かれているので、コード読むとか良さそう。

**Comment by y-yagi** [comment]
久しぶりに Gemfileみせっこ

**Comment by y-yagi** [comment]
WebAPIの設計についてとか

**Comment by willnet** [comment]
[Volt](http://voltframework.com/)

**Comment by y-yagi** [comment]
mrubyで遊ぶ。 [hone/mruby-cli](https://github.com/hone/mruby-cli) とか良さそう。

**Comment by willnet** [comment]
Ruby 2.3.0 の変更点チェック

**Comment by willnet** [comment]
ActiveRecord 以外の ORマッパを学ぶとかどうか

- [ROM » Home](http://rom-rb.org/)
- [jeremyevans/sequel](https://github.com/jeremyevans/sequel)

**Comment by y-yagi** [comment]
認証系gemについて
* [CanCanCommunity/cancancan](https://github.com/CanCanCommunity/cancancan)
* [elabs/pundit](https://github.com/elabs/pundit)
* [kyuden/banken](https://github.com/kyuden/banken)

(基調講演をお願い出来るのでは、という思惑もあります)

**Comment by willnet** [comment]
なるほど banken

**Comment by willnet** [comment]
> なるほど banken

@kyuden さんに基調講演、口頭でお願いしておきました :smiling_imp:

**Comment by ken1flan** [comment]
:heart_eyes_cat:

**Comment by y-yagi** [comment]
[Trailblazer: A High-Level Architecture For The Web](http://trailblazer.to/) を試す

**Comment by willnet** [comment]
rails-assets 以外の選択肢について

- bower
- npm
- browserify
- webpack

など

**Comment by willnet** [comment]
[Ruby on Rails: Doctrine](http://rubyonrails.org/doctrine)

**Comment by y-yagi** [comment]
Goで遊ぶ

**Comment by willnet** [comment]
sinatra 2.0

[zzak.io/log](http://zzak.io/log/2016-04-18-the-road-to-sinatra-2.0.html?utm_source=rubyweekly&utm_medium=email)

**Comment by y-yagi** [comment]
[Roda: Routing Tree Web Toolkit](http://roda.jeremyevans.net/)

**Comment by y-yagi** [comment]
[Ruby Object Mapper](http://rom-rb.org/)

**Comment by y-yagi** [comment]
[Introduction | Ruby Tricks, Idiomatic Ruby, Refactorings and Best Practices](http://best-ruby.com/) を読む

**Comment by y-yagi** [comment]
[dry-rb - Home](http://dry-rb.org/) を見てみる。 
"dry-rb is a collection of next-generation Ruby libraries,
each intended to encapsulate a common task" らしい。

**Comment by willnet** [comment]
久しぶりに Rails ソースコードリーディング。
各自Railsのソースコード(の一部)を事前に読んできて、面白かった内容をシェアする会。

**Comment by y-yagi** [comment]
ちょっと早いけどRuby 2.4の新機能を眺める
[New Features in Ruby 2\.4 \- BlockScore Blog](https://blog.blockscore.com/new-features-in-ruby-2-4)

**Comment by y-yagi** [comment]
(実際にやったお題に何かマークつけたいなあ)

**Comment by willnet** [comment]
rom 2.0 になったらしい

http://rom-rb.org/blog/rom-2-0-0-released/?utm_source=rubyweekly&utm_medium=email

**Comment by y-yagi** [comment]
ふむ。タイミングも良さそうだし、次回(8/16(火))、romについてをやってみても良いですかねえ

**Comment by willnet** [comment]
https://github.com/puma/puma-dev

**Comment by y-yagi** [comment]
最近作ったモノ(サービス、ライブラリ等何でもOK)をシェアする会
[Ginza\.rb 第24回 最近気になった事は何ですか? 調べた内容をシェアしてみよう！ \- Ginza\.rb \| Doorkeeper](https://ginzarb.doorkeeper.jp/events/26537) みたいな感じで

**Comment by y-yagi** [comment]
rackコードリーティング。 HTTPのリクエストを受けてレスポンス返すまでの一連の流れを追ってみるとか。

**Comment by willnet** [comment]
Ruby標準ライブラリを眺める [ライブラリ一覧 (Ruby 2.3.0)](http://docs.ruby-lang.org/ja/2.3.0/library/index.html)

**Comment by willnet** [comment]
> (実際にやったお題に何かマークつけたいなあ)

絵文字のリアクションつけるのどうか。 🎉 とか

**Comment by y-yagi** [comment]
> :tada: とか

良さそう。やってみよう。

**Comment by y-yagi** [comment]
一通りつけてみた

**Comment by y-yagi** [comment]
[Concurrent Ruby](https://github.com/ruby-concurrency/concurrent-ruby) のコードリーディング

**Comment by y-yagi** [comment]
> ActiveRecord 以外の ORマッパを学ぶとかどうか

> ROM » Home
> jeremyevans/sequel

ROMはやったのでsequel

**Comment by ken1flan** [comment]
Ruby 2.4

**Comment by y-yagi** [comment]
(Ruby 2.4はですでにもうあがってるんですよ実は https://github.com/ginzarb/meetups/issues/15#issuecomment-234755684 )

**Comment by y-yagi** [comment]
[eliotsykes/real\-world\-rails: Real World Rails applications and their open source codebases for developers to learn from](https://github.com/eliotsykes/real-world-rails)
をながめる

**Comment by willnet** [comment]
なるほど。たくさんRailsアプリあるな [real-world-rails/apps at master · eliotsykes/real-world-rails](https://github.com/eliotsykes/real-world-rails/tree/master/apps)

**Comment by y-yagi** [comment]
[hanami](http://hanamirb.org/)の今を追う。 Lotus取り上げたの1年以上前だから、多少変化ありそう。

**Comment by y-yagi** [comment]
みんなで [eliotsykes/rails\-security\-checklist: Community\-driven Rails Security Checklist](https://github.com/eliotsykes/rails-security-checklist) をみる

**Comment by y-yagi** [comment]
そろそろmruby

**Comment by y-yagi** [comment]
[tootsuite/mastodon: A GNU Social\-compatible microblogging server](https://github.com/tootsuite/mastodon) のコードリーディング

**Comment by y-yagi** [comment]
[github/github\-ds: A collection of Ruby libraries for working with SQL on top of ActiveRecord's connection](https://github.com/github/github-ds) をみる

**Comment by y-yagi** [comment]
Gemfile見せっこ久し振りにやる

**Comment by y-yagi** [comment]
Railsアップグレードの知見共有会。

**Comment by y-yagi** [comment]
[rails/activestorage: Store files in Rails applications](https://github.com/rails/activestorage)

**Comment by y-yagi** [comment]
RubyKaigi感想会2017

**Comment by y-yagi** [comment]
https://github.com/gitlabhq/gitlabhq のコードリーディング

**Comment by willnet** [comment]
[boazsegev/iodine: iodine - HTTP / Websocket Server with Pub/Sub support, optimized for Ruby MRI on Linux / BSD](https://github.com/boazsegev/iodine)

**Comment by y-yagi** [comment]
年末なので、雑に今年頑張った事報告会。
[Ginza\.rb 第24回 最近気になった事は何ですか? 調べた内容をシェアしてみよう！ \- Ginza\.rb \| Doorkeeper](https://ginzarb.doorkeeper.jp/events/26537)
みたいな感じで。資料はなくても勿論OK。

**Comment by y-yagi** [comment]
https://ginzarb.doorkeeper.jp/events/61559
の [GitHub organization](https://github.com/github) 版。

**Comment by y-yagi** [comment]
毎度おなじみRuby 2.5

**Comment by y-yagi** [comment]
Rails 5.2

タイミング的に、12月にRuby 2.5やって、1月にRails 5.2とかが良いかなあ

**Comment by willnet** [comment]
[Railsのきれいなコードのお題案 · Issue #1 · clean-rails-ja/conversation](https://github.com/clean-rails-ja/conversation/issues/1)

**Comment by y-yagi** [comment]
でぃーえいちえいちっていう有名なYouTuberがいるらしいので、みんなで動画をみる
https://www.youtube.com/channel/UCUkM9uMpWatT7gVWShgtKFw

**Comment by y-yagi** [comment]
https://github.com/discourse
配下、大量のライブラリ(Ruby以外も)があるので、discourse本体とは別にそれを見る会があっても良いかなあ

**Comment by y-yagi** [comment]
[openblockchains/programming\-blockchains\-step\-by\-step: Programming Blockchains Step\-by\-Step book / guide\. Let's build blockchains from scratch \(zero\) step by step\. Let's start with crypto hashes\.\.\.](https://github.com/openblockchains/programming-blockchains-step-by-step)

**Comment by willnet** [comment]
Rubyやその周辺の本で、おすすめなやつの概要を紹介し合う回とかどうか

**Comment by willnet** [comment]
dev.toのコードリーディング https://dev.to/ben/the-devto-codebase-will-go-open-source-on-august-8-2kia

**Comment by willnet** [comment]
[Stimulus: A modest JavaScript framework for the HTML you already have.](https://stimulusjs.org/)

**Comment by y-yagi** [comment]
https://github.com/rails-engine にあるgemを眺める

**Comment by y-yagi** [comment]
JSON APIを生成する際のライブラリ何使ってますか相談会(AMSがほぼ死亡状態っぽいので https://github.com/rails-api/active_model_serializers#status-of-ams )

**Comment by willnet** [comment]
死亡というほどではなさそうだけど停滞してそう

[vasilakisfil/SimpleAMS: Modern Ruby serializers](https://github.com/vasilakisfil/SimpleAMS) とかの比較的新しいやつ使ってる人いたら話聞きたいですね

**Comment by y-yagi** [comment]
ぼちぼちRails 6.0

**Comment by y-yagi** [comment]
OrganizationではなくGitHubの個人アカウントのリポジトリ(及びその人がコントリビュートしているプロジェクト)をみる。

https://github.com/janko 
とか
https://github.com/ioquatix
とか

**Comment by y-yagi** [comment]
Sorbet https://sorbet.org/blog/2019/06/20/open-sourcing-sorbet
