### ISSUE TITLE
議事録リポジトリ or wiki を作る

### ISSUE THREAD

**Issue by willnet** [ginzarb/meetups#166]
[第22回 · ginzarb/meetups Wiki](https://github.com/ginzarb/meetups/wiki/%E7%AC%AC22%E5%9B%9E)のTRYに出ていたのでした(忘れてた＞＜)。

**Comment by y-yagi** [comment]
(すっかり忘れてた…)
履歴も管理出来るし、準備も特に手間掛らないので、Wikiで良さそうな気もしますねえ。

ただ、`meeups`リポのwikiだと、KPTと混ざっちゃうので、議事録用リポジトリ作ってそっちのwikiでやる方が良さそうかもですねえ。
(KPTと混ぜちゃっても良い気もしますが)

**Comment by y-yagi** [comment]
とりあえずリポジトリ([ginzarb/proceedings](https://github.com/ginzarb/proceedings))作ったので、今日のミートアップをまとめるところからやってみようと思います。

**Comment by y-yagi** [comment]
↑で作ったリポジトリでとりあえずやっていこうと思います。 問題・もっとこうやった方が良くない? というのがあったら、再オープンするとして、一旦くろーずします。
