### ISSUE TITLE
ginzarb のハッシュタグを拾って idobata にポストしたい

### ISSUE THREAD

**Issue by willnet** [ginzarb/meetups#198]
sendabaya.rb がやってて良さそうだったので真似たい

**Comment by 5704k3** [comment]
たしかよちよち.rbも同じようにしてましたね

**Comment by willnet** [comment]
> たしかよちよち.rbも同じようにしてましたね

おーなるほど。じゃよちよち発なのかな

**Comment by willnet** [comment]
![image](https://cloud.githubusercontent.com/assets/82371/8300935/067d599e-19c5-11e5-9485-2765f9f58646.png)

**Comment by willnet** [comment]
> twitterとmakerの組わせでidobataにweb request出してる

```
url: idobataのhook url
method: POST
Content-Type: x-www-form-urlencoded
body:
format=html&source=<img src="{{UserImageUrl}}" width="30px" height="30px"><a href="https://twitter.com/{{UserName}}">@{{UserName}}</a> <a href="{{LinkToTweet}}">{{CreatedAt}}</a> {{TweetEmbedCode}}
```

**Comment by willnet** [comment]
ifttt のレシピの作り方

1. twitter search で `#ginzarb` をキーワードに検索する
2. maker で、一個前のコメントの内容を設定

これだけで出来たぽい

**Comment by willnet** [comment]
![寿司ゆき:happy](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/24.png)

**Comment by y-yagi** [comment]
![寿司ゆき:wasabi](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/29.png)
