### ISSUE TITLE
「ウェディングへの道」を作る

### ISSUE THREAD

**Issue by willnet** [ginzarb/meetups#238]

**Comment by willnet** [comment]
参考: [万葉への道](https://www.evernote.com/shard/s5/sh/58fe07bf-2f01-4acf-9452-4e9684323fe8/69f678003ce3df52)

**Comment by y-yagi** [comment]
「ウェディングへの道」、折角画像とって頂いたので、どっかにそれようのページ作りたい気持ちがあるのですが、
コンテンツどこに置くのが良いのでしょうねえ? 

http://ginzarb.github.io/ とか、gistとか?

**Comment by willnet** [comment]
100% みんなのウェディングさんを利用できるとは限らないので、github pages より gist のほうがいいかも

**Comment by willnet** [comment]
で、リンクを doorkeeper に貼る流れで

**Comment by y-yagi** [comment]
ヨサソウ！

**Comment by ken1flan** [comment]
よさそう :+1:

**Comment by y-yagi** [comment]
作ってみた

https://gist.github.com/y-yagi/ef7a0c4b3cd289b9c00b#file-ginzarb-md

(@ken1flan のアカウントで作ってもらった方が良いかも?)

**Comment by willnet** [comment]
:+1:

**Comment by ken1flan** [comment]
:+1: 
たしかに自分のアカウントのほうがいいかも。
あとでうつすー。

しかし、迷う人は、募集ページの地図をそもそも見ていない…なんてことはないよね。うん。

**Comment by willnet** [comment]
このIssueのステータスって「地図はできたけど doorkeeper に貼ってない」なんでしたっけ

**Comment by y-yagi** [comment]
doorkeeperにはもう貼ってるんですが、

> たしかに自分のアカウントのほうがいいかも。
> あとでうつすー。

@ken1flan のこれ待ち、という認識です

**Comment by willnet** [comment]
doorkeeper のどこですかね…見つけられなかった＞＜

前回のイベントページにはなさそう

[Ginza.rb 第29回 オブジェクト指向を取り戻せ？ Lotus Frameworkについて学ぼう！！ - Ginza.rb | Doorkeeper](https://ginzarb.doorkeeper.jp/events/34366)

**Comment by y-yagi** [comment]
`最寄り駅`のところの、`(駅から会場まで)`が↑のgistへのリンクになってますー

**Comment by willnet** [comment]
おおお

**Comment by willnet** [comment]
あった

**Comment by ken1flan** [comment]
まるまるコピペしたけど…だいじょうぶかしら。
https://gist.github.com/ken1flan/c5d713f0176c0146d3b1#file-road-to-wedding-md

**Comment by y-yagi** [comment]
:+1:
