### ISSUE TITLE
第53回で使うGemfile 回収場所

### ISSUE THREAD

**Issue by y-yagi** [ginzarb/meetups#609]
みせっこするGemfileへのリンク/Gistへのパスなどを、ここのリンクに書いて下さいー

**Comment by y-yagi** [comment]
こんな感じ
https://gist.github.com/y-yagi/8909044

**Comment by rilmayer** [comment]
よろしくお願いします〜。
https://gist.github.com/rilmayer/37d82c0d036adb7139c075e05205521f

**Comment by ota42y** [comment]
https://gist.github.com/ota42y/d3cffba1d20320b0533ce2e36044c218

**Comment by willnet** [comment]
わいわい

https://gist.github.com/willnet/044a169656ad6c7e6809c80ac8a620bd

**Comment by y-yagi** [comment]
おしまい
