### ISSUE TITLE
お題

### ISSUE THREAD

**Issue by y-yagi** [ginzarb/meetups#964]
ミートアップのお題になりそうなものを思いついたらメモっておくスレ Part 2です。昔の： #15, #122。

**Comment by y-yagi** [comment]
(前もあがってた気がするが) [socketry/falcon](https://github.com/socketry/falcon)。 ついでにNGINX Unitも https://unit.nginx.org/configuration/#configuration-ruby 。

**Comment by willnet** [comment]
サーバつながりで(前も書いた気がするけど) [boazsegev/iodine: iodine - HTTP / WebSockets Server for Ruby with Pub/Sub support](https://github.com/boazsegev/iodine)

**Comment by y-yagi** [comment]
[ohler55/agoo: A High Performance HTTP Server for Ruby](https://github.com/ohler55/agoo) 
サーバって書いてあるけど、GraphQL用の機能もあったりして、HTTPサーバ+フレームワークな感じらしい。

**Comment by y-yagi** [comment]
[codetriage/codetriage](https://github.com/codetriage/codetriage)のコード・リーディング

**Comment by y-yagi** [comment]
最近のCI事情について(雑にはなしたい)

**Comment by willnet** [comment]
https://github.com/fxn/zeitwerk コードリーディング

お手伝い先ですでに2回実施済みだけど1時間でざっと概要と、主要なコードを読むのができる規模

**Comment by y-yagi** [comment]
https://github.com/rubyapi/rubyapi のコードリーディング(フロントStimulusだ)

**Comment by y-yagi** [comment]
[gsamokovarov/break](https://github.com/gsamokovarov/break) を試しながら、みんなデバッギングってどうやってやってますか、というのを雑に話す会

**Comment by willnet** [comment]
[StimulusReflex](https://docs.stimulusreflex.com/)

stimulusの拡張で、サーバが送ったHTMLをいい感じに既存のとマージさせることで楽にSPAできるぞ！というやつらしい

**Comment by willnet** [comment]
[jeremyevans/rodauth: Ruby's Most Advanced Authentication Framework](https://github.com/jeremyevans/rodauth/) などの認証ライブラリについて話す会

**Comment by willnet** [comment]
[Prettier for Ruby goes v1.0 🎉 · Prettier](https://prettier.io/blog/2020/12/11/plugin-ruby-1.0.html)

**Comment by willnet** [comment]
https://hotwire.dev

**Comment by willnet** [comment]
このスレだいぶ古いので新設しましょうかね…

**Comment by y-yagi** [comment]
とじちゃえ
